# workflow name
name: CI Backup First

# master branch on push, auto run
on: 
  push:
    branches:
      - master
      
jobs:
  Backup:
    name: Backup To Private Project 
    runs-on: ubuntu-latest 
    
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository master branch
      uses: actions/checkout@master 
      
    - name: Setup Git Infomation
      run: | 
        git config --global user.name 'blak-kong' 
        git config --global user.email '546598185@qq.com'  
        
    - name: Setup SSH Private Key
      env:
        Token_Private_Keys: ${{ secrets.Token_Private_Keys }}
      run: |
        mkdir -p ~/.ssh/
        echo "$Token_Private_Keys" > ~/.ssh/id_rsa 
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 47.103.12.22 >> ~/.ssh/known_hosts
    
    - name: Get Latest Commit Message 
      run: |
        git log --pretty=format:"%s from Github Actions at `date +"%Y-%m-%d %H:%M:%S"`" --date=short -n 1  > commit-message.log
    
    - name: Backup To ESC Private Project
      env:
        ECS_VuePress: ${{ secrets.ECS_VuePress }}
      run: |
        git add .
        git commit -F ./commit-message.log
        git push --force --quiet ${ECS_VuePress} master