name: Build README

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Update README
      env:
        ESC_SSH: ${{ secrets.ESC_SSH }}
      run: |-
        python build_readme.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "546598185@qq.com"
        git config --global user.name "blak-kong"
        git pull
        git add -A
        git commit -m "Updated content" || exit 0
        git push